"""add cover photo and logo to restaurants

Revision ID: 1ca532270e96
Revises: cd13a009784f
Create Date: 2026-09-01 13:41:59.578536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ca532270e96'
down_revision: Union[str, None] = 'cd13a009784f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('cover_photo_url', sa.String(length=300), nullable=True))
    op.add_column('restaurants', sa.Column('cover_photo_data', sa.LargeBinary(), nullable=True))
    op.add_column('restaurants', sa.Column('cover_photo_content_type', sa.String(length=60), nullable=True))
    op.add_column('restaurants', sa.Column('logo_url', sa.String(length=300), nullable=True))
    op.add_column('restaurants', sa.Column('logo_data', sa.LargeBinary(), nullable=True))
    op.add_column('restaurants', sa.Column('logo_content_type', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'logo_content_type')
    op.drop_column('restaurants', 'logo_data')
    op.drop_column('restaurants', 'logo_url')
    op.drop_column('restaurants', 'cover_photo_content_type')
    op.drop_column('restaurants', 'cover_photo_data')
    op.drop_column('restaurants', 'cover_photo_url')
    # ### end Alembic commands ###
