"""add menu item options and order item selected options

Revision ID: 242d135e2c01
Revises: e306a07800cd
Create Date: 2026-08-24 14:37:20.012759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '242d135e2c01'
down_revision: Union[str, None] = 'e306a07800cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # F5-A2 (MARCHE_FRANCE.md) : options et suppléments d'un article (cuisson,
    # accompagnement, taille…) — voir menu/models.py. Trois tables neuves,
    # aucune colonne ajoutée à une table existante : pas de retrofit NOT NULL
    # à gérer ici.
    op.create_table('menu_item_option_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('allow_multiple', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_item_option_groups_menu_item_id'), 'menu_item_option_groups', ['menu_item_id'], unique=False)
    op.create_index(op.f('ix_menu_item_option_groups_restaurant_id'), 'menu_item_option_groups', ['restaurant_id'], unique=False)
    op.create_table('menu_item_option_choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('price_delta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['menu_item_option_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_item_option_choices_group_id'), 'menu_item_option_choices', ['group_id'], unique=False)
    op.create_table('order_item_option_choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('choice_id', sa.Integer(), nullable=True),
    sa.Column('group_name', sa.String(length=60), nullable=False),
    sa.Column('choice_name', sa.String(length=60), nullable=False),
    sa.Column('price_delta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['choice_id'], ['menu_item_option_choices.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_item_option_choices_order_item_id'), 'order_item_option_choices', ['order_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_item_option_choices_order_item_id'), table_name='order_item_option_choices')
    op.drop_table('order_item_option_choices')
    op.drop_index(op.f('ix_menu_item_option_choices_group_id'), table_name='menu_item_option_choices')
    op.drop_table('menu_item_option_choices')
    op.drop_index(op.f('ix_menu_item_option_groups_restaurant_id'), table_name='menu_item_option_groups')
    op.drop_index(op.f('ix_menu_item_option_groups_menu_item_id'), table_name='menu_item_option_groups')
    op.drop_table('menu_item_option_groups')
    # ### end Alembic commands ###
