"""add is_active and promo_gratuit to restaurants

Revision ID: 2976b3bc4f38
Revises: c3f81a9e2b56
Create Date: 2026-08-20 14:38:32.289031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2976b3bc4f38'
down_revision: Union[str, None] = 'c3f81a9e2b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default nécessaire : les deux colonnes sont NOT NULL et la table a
    # déjà des lignes (restaurants existants — pilotes facturés à la main par
    # setup_restaurant.py, comptes de démo). `is_active=true` par défaut les
    # laisse inchangés (déjà utilisables) ; seul /auth/register force
    # explicitement `False` pour un nouvel établissement (2026-08-20, voir
    # Restaurant.is_active). `promo_gratuit=false` : aucun restaurant existant
    # n'a de dérogation avant qu'un admin ne la pose à la main.
    op.add_column(
        'restaurants',
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.add_column(
        'restaurants',
        sa.Column('promo_gratuit', sa.Boolean(), nullable=False, server_default=sa.false()),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'promo_gratuit')
    op.drop_column('restaurants', 'is_active')
    # ### end Alembic commands ###
