"""add social links to restaurants

Revision ID: 52d242d3bb0b
Revises: 1ca532270e96
Create Date: 2026-09-01 14:35:13.042697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52d242d3bb0b'
down_revision: Union[str, None] = '1ca532270e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('facebook_url', sa.String(length=300), nullable=True))
    op.add_column('restaurants', sa.Column('instagram_url', sa.String(length=300), nullable=True))
    op.add_column('restaurants', sa.Column('tiktok_url', sa.String(length=300), nullable=True))
    op.add_column('restaurants', sa.Column('whatsapp_url', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'whatsapp_url')
    op.drop_column('restaurants', 'tiktok_url')
    op.drop_column('restaurants', 'instagram_url')
    op.drop_column('restaurants', 'facebook_url')
    # ### end Alembic commands ###
