"""add plan landmarks

Revision ID: 55a307a3bc86
Revises: 4c10f1f82e98
Create Date: 2026-09-07 22:23:08.037801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '55a307a3bc86'
down_revision: Union[str, None] = '4c10f1f82e98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_landmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('BAR', 'ENTRANCE', name='landmarkkind'), nullable=False),
    sa.Column('pos_x', sa.Float(), nullable=False),
    sa.Column('pos_y', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_landmarks_restaurant_id'), 'plan_landmarks', ['restaurant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_landmarks_restaurant_id'), table_name='plan_landmarks')
    op.drop_table('plan_landmarks')
    # ### end Alembic commands ###

    # DROP TABLE ne supprime pas le type Postgres créé pour la colonne enum
    # (contrairement à SQLite, où l'enum n'est qu'un VARCHAR + CHECK) — sans
    # ce nettoyage explicite, remonter après une descente échoue sur "type
    # landmarkkind already exists" (même piège déjà rencontré dans la
    # migration c2e7b41f8a90).
    postgresql.ENUM(name="landmarkkind").drop(op.get_bind(), checkfirst=True)
