"""initial schema

Revision ID: 81067c492c21
Revises: 
Create Date: 2026-08-12 10:49:07.403483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81067c492c21'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ramadan_mode_enabled', sa.Boolean(), nullable=False),
    sa.Column('iftar_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cafe_mode_enabled', sa.Boolean(), nullable=False),
    sa.Column('kitchen_sound_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('loyalty_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('reward_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'phone_number', name='uq_loyalty_restaurant_phone')
    )
    op.create_index(op.f('ix_loyalty_members_phone_number'), 'loyalty_members', ['phone_number'], unique=False)
    op.create_index(op.f('ix_loyalty_members_restaurant_id'), 'loyalty_members', ['restaurant_id'], unique=False)
    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(length=300), nullable=True),
    sa.Column('spice_level', sa.Integer(), nullable=False),
    sa.Column('allergens', sa.String(length=300), nullable=True),
    sa.Column('is_halal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_items_restaurant_id'), 'menu_items', ['restaurant_id'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('role', sa.Enum('WAITER', 'MANAGER', 'KITCHEN', name='staffrole'), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_staff_restaurant_id'), 'staff', ['restaurant_id'], unique=False)
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('qr_token', sa.String(length=64), nullable=False),
    sa.Column('assigned_staff_id', sa.Integer(), nullable=True),
    sa.Column('zone', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_token')
    )
    op.create_index(op.f('ix_tables_restaurant_id'), 'tables', ['restaurant_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_CONFIRMATION', 'CONFIRMED', 'SENT_TO_KITCHEN', 'IN_PREPARATION', 'READY', 'SERVED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_to_kitchen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('served_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('taken_by_staff_id', sa.Integer(), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_method', sa.Enum('CARD', 'CASH', name='paymentmethod'), nullable=True),
    sa.Column('payment_status', sa.Enum('UNPAID', 'PENDING', 'PAID', name='paymentstatus'), nullable=False),
    sa.Column('tip_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_ref', sa.String(length=120), nullable=True),
    sa.Column('loyalty_phone', sa.String(length=30), nullable=True),
    sa.Column('push_subscription', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.ForeignKeyConstraint(['taken_by_staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_restaurant_id'), 'orders', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_orders_table_id'), 'orders', ['table_id'], unique=False)
    op.create_table('waiter_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_staff_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by_staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waiter_calls_restaurant_id'), 'waiter_calls', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_waiter_calls_table_id'), 'waiter_calls', ['table_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_name', sa.String(length=120), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_waiter_calls_table_id'), table_name='waiter_calls')
    op.drop_index(op.f('ix_waiter_calls_restaurant_id'), table_name='waiter_calls')
    op.drop_table('waiter_calls')
    op.drop_index(op.f('ix_orders_table_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_restaurant_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_tables_restaurant_id'), table_name='tables')
    op.drop_table('tables')
    op.drop_index(op.f('ix_staff_restaurant_id'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_menu_items_restaurant_id'), table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index(op.f('ix_loyalty_members_restaurant_id'), table_name='loyalty_members')
    op.drop_index(op.f('ix_loyalty_members_phone_number'), table_name='loyalty_members')
    op.drop_table('loyalty_members')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
