"""add google review url to restaurants

Revision ID: a75721b32c6e
Revises: 52d242d3bb0b
Create Date: 2026-09-01 15:15:10.662043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a75721b32c6e'
down_revision: Union[str, None] = '52d242d3bb0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('google_review_url', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'google_review_url')
    # ### end Alembic commands ###
