"""add menu formulas and order formula lines

Revision ID: b5d3d4e04372
Revises: 242d135e2c01
Create Date: 2026-08-24 15:55:35.019798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d3d4e04372'
down_revision: Union[str, None] = '242d135e2c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_formulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_formulas_restaurant_id'), 'menu_formulas', ['restaurant_id'], unique=False)
    op.create_table('menu_formula_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formula_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['formula_id'], ['menu_formulas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_formula_slots_formula_id'), 'menu_formula_slots', ['formula_id'], unique=False)
    op.create_table('menu_formula_slot_items',
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['menu_formula_slots.id'], ),
    sa.PrimaryKeyConstraint('slot_id', 'menu_item_id')
    )
    op.create_table('order_formulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('formula_id', sa.Integer(), nullable=False),
    sa.Column('formula_name', sa.String(length=120), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('shared_with', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['formula_id'], ['menu_formulas.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_formulas_order_id'), 'order_formulas', ['order_id'], unique=False)
    op.create_table('order_formula_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_formula_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=True),
    sa.Column('slot_name', sa.String(length=60), nullable=False),
    sa.Column('menu_item_name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['order_formula_id'], ['order_formulas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_formula_selections_order_formula_id'), 'order_formula_selections', ['order_formula_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_formula_selections_order_formula_id'), table_name='order_formula_selections')
    op.drop_table('order_formula_selections')
    op.drop_index(op.f('ix_order_formulas_order_id'), table_name='order_formulas')
    op.drop_table('order_formulas')
    op.drop_table('menu_formula_slot_items')
    op.drop_index(op.f('ix_menu_formula_slots_formula_id'), table_name='menu_formula_slots')
    op.drop_table('menu_formula_slots')
    op.drop_index(op.f('ix_menu_formulas_restaurant_id'), table_name='menu_formulas')
    op.drop_table('menu_formulas')
    # ### end Alembic commands ###
