"""add launch promo fields to restaurants

Revision ID: cb1a4204472f
Revises: 2976b3bc4f38
Create Date: 2026-08-21 08:01:22.868741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb1a4204472f'
down_revision: Union[str, None] = '2976b3bc4f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default nécessaire : colonnes NOT NULL, table déjà peuplée.
    # launch_promo_granted=false pour tout restaurant existant : aucun n'a
    # jamais fait partie du lancement de l'offre. has_paid_for_subscription
    # =true : restaurants existants = pilotes/comptes de démo, une vraie
    # relation payante (voir le commentaire du modèle) — seul /auth/register
    # force explicitement false à la création.
    op.add_column(
        'restaurants',
        sa.Column('launch_promo_granted', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'restaurants',
        sa.Column('has_paid_for_subscription', sa.Boolean(), nullable=False, server_default=sa.true()),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'has_paid_for_subscription')
    op.drop_column('restaurants', 'launch_promo_granted')
    # ### end Alembic commands ###
