"""add platform admin dashboard

Revision ID: e0a7b7b1aad3
Revises: c3f81a9e2b56
Create Date: 2026-08-20 12:57:01.785533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0a7b7b1aad3'
down_revision: Union[str, None] = 'c3f81a9e2b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('dashboard_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_views_restaurant_id'), 'dashboard_views', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_dashboard_views_viewed_at'), 'dashboard_views', ['viewed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dashboard_views_viewed_at'), table_name='dashboard_views')
    op.drop_index(op.f('ix_dashboard_views_restaurant_id'), table_name='dashboard_views')
    op.drop_table('dashboard_views')
    op.drop_table('platform_admins')
    # ### end Alembic commands ###
